// AUTO-GENERATED by packages/shared-types/scripts/gen-types.mjs from the Pydantic schema.
// Do not edit by hand: run `pnpm gen:types` after changing apps/api/src/app/agent/schema.py.

export type Severity = "critical" | "high" | "medium" | "low";
export type Category = "security" | "performance" | "correctness" | "style" | "maintainability" | "best-practice";
export type Evidence = "tool_verified" | "diff_visible" | "verified_fact" | "inference";
export type DiffSide = "RIGHT" | "LEFT";
export type DropReason = "target_line_mismatch" | "line_out_of_range" | "syntax_invalid_suggestion" | "incoherent_suggestion" | "line_not_in_diff" | "file_not_in_context" | "validator_error";
export type ReviewStatus = "queued" | "running" | "done" | "failed" | "skipped" | "canceled" | "partial" | "rate_limited" | "budget_exhausted";
export type TerminalStatus = "success" | "skipped" | "failed" | "canceled" | "partial" | "rate_limited" | "budget_exhausted";

export interface Finding {
  category: Category;
  /** Calibrated confidence this finding is correct and actionable. 95-100: verified via tool call, no plausible counter-argument. 80-94: strong evidence from diff + context. 60-79: plausible but unverified. 40-59: speculative (only submit if severity is critical). Below 40: do not submit. */
  confidence: number;
  evidence: Evidence;
  /** ID from verified_facts.yaml. Required when evidence == 'verified_fact'. */
  evidence_fact_id?: string | null;
  /** Tool names called to verify this finding. Required when evidence == 'tool_verified'. */
  evidence_tool_calls?: string[] | null;
  file_path: string;
  /** Stable id for delivery markers and outcome tracking (optional). */
  finding_id?: string | null;
  /** True if the finding's correctness depends on external vendor, platform, framework, or library behavior. See vendor-claim rules. */
  is_vendor_claim?: boolean;
  line_end?: number | null;
  line_start: number;
  message: string;
  new_line_no?: number | null;
  old_line_no?: number | null;
  /** Best-effort diff hunk identifier used for anchor diagnostics. */
  patch_hunk?: string | null;
  severity: Severity;
  /** GitHub diff side anchor for line. */
  side?: DiffSide;
  /** GitHub diff side anchor for start_line in multi-line comments. */
  start_side?: DiffSide | null;
  /** Code block to replace lines with */
  suggestion?: string | null;
  /** The exact content of line_start as it appears in the file at HEAD. */
  target_line_content: string;
  /** True if a tool call was made that touched this file during the review. */
  verified_via_tool?: boolean;
}

export const SEVERITIES: readonly Severity[] = ["critical","high","medium","low"];
export const CATEGORIES: readonly Category[] = ["security","performance","correctness","style","maintainability","best-practice"];
export const DROP_REASONS: readonly DropReason[] = ["target_line_mismatch","line_out_of_range","syntax_invalid_suggestion","incoherent_suggestion","line_not_in_diff","file_not_in_context","validator_error"];
export const REVIEW_STATUSES: readonly ReviewStatus[] = ["queued","running","done","failed","skipped","canceled","partial","rate_limited","budget_exhausted"];
