import type { Metadata } from "next";
import Link from "next/link";

import { StaticDocument } from "@/components/layout/static-document";
import { buildSeoMetadata } from "@/lib/seo";

export const metadata: Metadata = buildSeoMetadata({
  title: "Terms and Conditions",
  description:
    "Review Nash AI terms and conditions, including acceptable use, AI output disclaimers, and responsibility boundaries.",
  path: "/terms",
});

export default function TermsPage() {
  return (
    <main className="static-document-shell">
      <StaticDocument
        title="Terms & Conditions"
        description="Last updated: April 27, 2026. These terms describe use of Nash AI as an agentic code review service. Customize for your legal entity, jurisdiction, and commercial model."
      >
        <h2 className="static-document-h2">Agreement</h2>
        <p>
          By accessing or using Nash AI (the &quot;Service&quot;), you agree to these Terms & Conditions
          (&quot;Terms&quot;). If you are using the Service on behalf of an organization, you represent that you
          have authority to bind that organization. If you do not agree, do not use the Service.
        </p>

        <h2 className="static-document-h2">The Service</h2>
        <p>
          Nash AI connects to GitHub as an application, ingests pull request events and repository context you
          authorize, runs automated &quot;agentic&quot; review workflows using third-party AI models, and may post
          review comments or related artifacts back to GitHub. Features, limits, and availability depend on your
          configuration and hosting environment.
        </p>

        <h2 className="static-document-h2">GitHub and third-party terms</h2>
        <p>
          Your use of GitHub remains governed by{" "}
          <a href="https://docs.github.com/site-policy/github-terms/github-terms-of-service" target="_blank" rel="noopener noreferrer">
            GitHub&apos;s Terms of Service
          </a>{" "}
          and related policies. AI features may send portions of your repository content to external model providers;
          those providers&apos; terms and privacy policies also apply to their processing.
        </p>

        <h2 className="static-document-h2">Accounts and security</h2>
        <p>
          You are responsible for maintaining the security of credentials tied to your deployment, for actions taken
          through your GitHub installation, and for ensuring that automation complies with your employer&apos;s
          policies and applicable law. Notify the operator promptly if you suspect unauthorized access.
        </p>

        <h2 className="static-document-h2">Acceptable use</h2>
        <p>You agree not to misuse the Service. Examples of misuse include:</p>
        <ul className="static-document-list">
          <li>Attempting to probe, disrupt, or bypass security controls or rate limits;</li>
          <li>Using the Service to violate intellectual property, export, sanctions, or privacy laws;</li>
          <li>Transmitting malware, spam, or unlawful content through integrations;</li>
          <li>Misrepresenting AI-generated review output as human-written guarantees.</li>
        </ul>

        <h2 className="static-document-h2">Intellectual property</h2>
        <p>
          You retain your rights in your code and content. To operate the Service, you grant a limited license to
          process, transmit, store, and display that content only as needed to provide reviews and run the product.
          The Nash AI software, branding, and documentation are owned by their respective licensors and licensed
          under the terms of the open-source license published in the repository unless otherwise stated.
        </p>

        <h2 className="static-document-h2">AI outputs and disclaimers</h2>
        <p>
          Reviews, suggestions, and summaries are generated by probabilistic models and tools. They may be
          incorrect, incomplete, or unsuitable for your security or compliance needs. The Service is a
          decision-support tool: <strong>you remain responsible</strong> for validating changes, running tests, and
          approving merges. The Service is provided <strong>&quot;as is&quot;</strong> without warranties of any
          kind, whether express or implied, including merchantability, fitness for a particular purpose, and
          non-infringement, to the fullest extent permitted by law.
        </p>

        <h2 className="static-document-h2">Limitation of liability</h2>
        <p>
          To the fullest extent permitted by law, neither Nash AI&apos;s operators nor contributors will be liable
          for any indirect, incidental, special, consequential, or punitive damages, or for loss of profits, data,
          or goodwill, arising from your use of the Service. Aggregate liability for direct damages should be limited
          to the greater of amounts you paid for the Service in the twelve months preceding the claim or zero if the
          Service is provided without charge—adjust this cap if you offer paid plans.
        </p>

        <h2 className="static-document-h2">Indemnity</h2>
        <p>
          You will defend and indemnify the operators and contributors against claims arising from your content,
          your violation of these Terms, or your misuse of GitHub or model providers, subject to applicable law and
          any caps you negotiate for enterprise customers.
        </p>

        <h2 className="static-document-h2">Suspension and termination</h2>
        <p>
          We may suspend or terminate access for conduct that risks the Service or other users, or as required by
          law. You may stop using the Service at any time by uninstalling the GitHub App and ceasing use of the
          dashboard. Provisions that by their nature should survive (disclaimers, liability limits, indemnity) survive
          termination.
        </p>

        <h2 className="static-document-h2">Changes</h2>
        <p>
          We may modify these Terms by posting an updated version and revising the &quot;Last updated&quot; date.
          Continued use after changes become effective constitutes acceptance unless applicable law requires
          additional notice or consent.
        </p>

        <h2 className="static-document-h2">Governing law</h2>
        <p>
          Choose the law and venue that fits your operating entity (for example the state or country of
          incorporation). Until you set that explicitly, disputes should be resolved in good faith negotiation, then
          in courts located where the maintainer designates—replace this paragraph with specific jurisdiction language
          from your counsel.
        </p>

        <h2 className="static-document-h2">Contact</h2>
        <p>
          Questions about these Terms can be directed through the{" "}
          <a href="https://github.com/jigargor/nash-ai" target="_blank" rel="noopener noreferrer">
            GitHub repository
          </a>
          .
        </p>
        <p>
          For data processing details, review the <Link href="/privacy">Privacy Policy</Link>. For project overview
          and product intent, see <Link href="/about">About Nash AI</Link>.
        </p>
      </StaticDocument>
    </main>
  );
}
