version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      dependencies:
        dependency-type: "all"
    labels:
      - "dependencies"
      - "python"
    target-branch: "develop"


  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      dependencies:
        dependency-type: "all"
    labels:
      - "dependencies"
      - "javascript"
    target-branch: "develop"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      dependencies:
        dependency-type: "all"
    labels:
      - "dependencies"
      - "github-actions"
    target-branch: "develop"