-- Deprecated file kept only as a pointer for historical local setups.
-- Canonical schema source: Alembic migrations in apps/api/alembic/versions/.
-- Apply schema changes with:
--   uv run alembic upgrade head
