"""create core tables

Revision ID: 03899c5db8ed
Revises: 
Create Date: 2026-04-17 16:39:07.309312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '03899c5db8ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('account_login', sa.Text(), nullable=False),
    sa.Column('account_type', sa.Text(), nullable=False),
    sa.Column('installed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('suspended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('token_enc', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    op.create_table('repo_configs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_full_name', sa.Text(), nullable=False),
    sa.Column('config_yaml', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.installation_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id', 'repo_full_name')
    )
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_full_name', sa.Text(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('pr_head_sha', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.installation_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('reviews_repo_pr', 'reviews', ['repo_full_name', 'pr_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('reviews_repo_pr', table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('repo_configs')
    op.drop_table('users')
    op.drop_table('installations')
    # ### end Alembic commands ###
