#!/usr/bin/env node
/**
 * Generate packages/shared-types/src/generated.ts from the Pydantic JSON schema exported by
 * apps/api/scripts/export_shared_schema.py. Deterministic output; CI fails on drift.
 *
 *   pnpm gen:types
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemaPath = resolve(here, "..", "generated", "pydantic-schema.json");
const outPath = resolve(here, "..", "src", "generated.ts");

const schema = JSON.parse(readFileSync(schemaPath, "utf8"));

function union(values) {
  return values.map((value) => JSON.stringify(value)).join(" | ");
}

function tsType(prop, defs) {
  if (!prop) return "unknown";
  if (prop.$ref) {
    const name = prop.$ref.split("/").pop();
    const def = defs[name];
    return def ? tsType(def, defs) : name;
  }
  if (prop.enum) return union(prop.enum);
  if (prop.anyOf) {
    const parts = prop.anyOf.map((item) => tsType(item, defs));
    return [...new Set(parts)].join(" | ");
  }
  switch (prop.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array":
      return `${wrap(tsType(prop.items, defs))}[]`;
    case "object":
      if (prop.additionalProperties && typeof prop.additionalProperties === "object") {
        return `Record<string, ${tsType(prop.additionalProperties, defs)}>`;
      }
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

function wrap(type) {
  return type.includes(" | ") ? `(${type})` : type;
}

function renderInterface(name, modelSchema, aliases) {
  const defs = modelSchema.$defs ?? {};
  const required = new Set(modelSchema.required ?? []);
  const lines = [`export interface ${name} {`];
  for (const [field, prop] of Object.entries(modelSchema.properties ?? {})) {
    const alias = aliases[field];
    const type = alias ?? tsType(prop, defs);
    const optional = required.has(field) ? "" : "?";
    const doc = prop.description ? `  /** ${prop.description.replace(/\*\//g, "*\\/")} */\n` : "";
    lines.push(`${doc}  ${field}${optional}: ${type};`);
  }
  lines.push("}");
  return lines.join("\n");
}

const finding = schema.finding;
const props = finding.properties;

const out = [
  "// AUTO-GENERATED by packages/shared-types/scripts/gen-types.mjs from the Pydantic schema.",
  "// Do not edit by hand: run `pnpm gen:types` after changing apps/api/src/app/agent/schema.py.",
  "",
  `export type Severity = ${union(props.severity.enum)};`,
  `export type Category = ${union(props.category.enum)};`,
  `export type Evidence = ${union(props.evidence.enum)};`,
  `export type DiffSide = ${union(props.side.enum)};`,
  `export type DropReason = ${union(schema.drop_reasons)};`,
  `export type ReviewStatus = ${union(schema.review_statuses)};`,
  `export type TerminalStatus = ${union(schema.terminal_statuses)};`,
  "",
  renderInterface("Finding", finding, {
    severity: "Severity",
    category: "Category",
    evidence: "Evidence",
    side: "DiffSide",
    start_side: "DiffSide | null",
  }),
  "",
  `export const SEVERITIES: readonly Severity[] = ${JSON.stringify(props.severity.enum)};`,
  `export const CATEGORIES: readonly Category[] = ${JSON.stringify(props.category.enum)};`,
  `export const DROP_REASONS: readonly DropReason[] = ${JSON.stringify(schema.drop_reasons)};`,
  `export const REVIEW_STATUSES: readonly ReviewStatus[] = ${JSON.stringify(schema.review_statuses)};`,
  "",
].join("\n");

writeFileSync(outPath, out, "utf8");
console.log(`wrote ${outPath}`);
